### ISSUE TITLE
system tray icon

### ISSUE THREAD

**Issue by thesilentarrow** [roldanjrCodeArts9711/productivity-timer#91] opened 2020-06-26 10:40 UTC
Every time I hide the timer a new icon is being created without removing the old one. Thus I end up with multiple icons. and show the app option is also not working.

**Comment by roldanjrCodeArts9711** [comment] 2020-06-26 14:06
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
Add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - App Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by thesilentarrow** [comment] 2020-06-27 05:52
![image](https://user-images.githubusercontent.com/61072494/85915738-a81f7e80-b867-11ea-8d18-56ac38ed79ce.png)
As you can see on the top right corner multiple icons are being created.
A new icon is being created whenever I use Alt+Shift+H without removing the old one.
I am using ubuntu 20.04
timer v 2.10.4-beta

**Comment by roldanjrCodeArts9711** [comment] 2020-06-27 08:37
Thank you @thesilentarrow . I will try to fix that as soon as possible. Just minimize it for the mean time rather than hiding it.

**Comment by roldanjrCodeArts9711** [comment] 2020-06-27 09:11
Did you installed it using snap? Please let me know.

**Comment by thesilentarrow** [comment] 2020-06-27 10:56
yes

**Comment by roldanjrCodeArts9711** [comment] 2020-06-27 12:46
> quick quesion- does it shows how much I studied in a week or month?

Not yet but it is now included on app's roadmap. Feature requested mention here #68 . 

> and it would be good if the timer asks us to start after the break instead of automatically starting.

I think I can't do that because I used the app all the time and I don't want to always start the timer every time.

**Comment by roldanjrCodeArts9711** [comment] 2020-06-28 12:38
I'm busy, but I just released v2.10.5-beta for snap today. 

Just  do `sudo snap refresh productivity-timer` using terminal to be updated right away
or just wait that snapcraft will install the new update for you.

I'm not 100% sure if the update will solve the issue because I'm not experiencing that problem on my Windows and Manjaro Linux. Please let me know if it solves your problem. Thank you.

**Comment by roldanjrCodeArts9711** [comment] 2020-06-29 11:33
> and it would be good if the timer asks us to start after the break instead of automatically starting.

I think you have a point. I will add it on my next release. Thank you @thesilentarrow .

**Comment by roldanjrCodeArts9711** [comment] 2020-07-05 11:42
I think I need to close this issue. Just open it again if you want.

**Closed by roldanjrCodeArts9711** 2020-07-05 11:42 UTC
Labels: bug
