### ISSUE TITLE
Bug Report: CPU usage is > 10%

### ISSUE THREAD

**Issue by moltar** [roldanjrCodeArts9711/productivity-timer#83] opened 2020-06-17 01:53 UTC
**Describe the bug**

The CPU usage seems to be extremely high for a timer app.

**To Reproduce**

Run the timer, check Activity Monitor on macOS.

**Expected behavior**

To have sub 1% CPU usage.

**Screenshots**

<img width="620" alt="image" src="https://user-images.githubusercontent.com/491247/84846027-1ac67800-b078-11ea-9951-1c7c1ec575e7.png">

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Version 10.15.4 (19E287)

**Additional context**

This only happens Timer tab is open. If I switch the tab to another one (e.g. Settings), then the usage subsides. So I am guessing it's the countdown timer itself that is taking up all of the CPU.

**Comment by roldanjrCodeArts9711** [comment] 2020-06-17 04:46
> **Describe the bug**
> 
> The CPU usage seems to be extremely high for a timer app.
> 
> **To Reproduce**
> 
> Run the timer, check Activity Monitor on macOS.
> 
> **Expected behavior**
> 
> To have sub 1% CPU usage.
> 
> **Screenshots**
> 
> <img alt="image" width="620" src="https://user-images.githubusercontent.com/491247/84846027-1ac67800-b078-11ea-9951-1c7c1ec575e7.png">
> 
> **Desktop (please complete the following information):**
> 
> * OS: macOS Catalina
> * Version 10.15.4 (19E287)
> 
> **Additional context**
> 
> This only happens Timer tab is open. If I switch the tab to another one (e.g. Settings), then the usage subsides. So I am guessing it's the countdown timer itself that is taking up all of the CPU.

You're right @moltar. It is mention also here #62 by @sekwah41 . 

Just try to `disabled` Timer Animation. It might due to High Frame Rate. 
I just noticed that It happened to users laptop with High Graphics Card. 

I hope disabling Timer Animation will help.

**Comment by sekwah41** [comment] 2020-06-17 13:25
I can confirm. The issue is electron is trying to animate it at as many frames a second as it can. Due to the type of elements, it is redrawing electron isn't exactly the most efficient at doing this which I doubt is an issue in their eyes as most animations are only temporary. Disabling this setting changes it to a fraction of the performance hit.

**Comment by moltar** [comment] 2020-06-18 01:05
Yes, that does make it better. Thanks! :)

**Comment by sekwah41** [comment] 2020-06-18 02:49
If this issue is resolved id suggest closing it :)

Some benefits may be found in launch arguments for electron though I don't believe this sort of fine-tuning should be a general issue for this application as it seems more of an electron issue unless there are specific launch arguments that could be configured though I believe by default it has things such as vsync enabled.

**Comment by roldanjrCodeArts9711** [comment] 2020-06-18 04:47
Thank you @sekwah41 .

**Closed** 2020-06-20 02:41 UTC

**Comment by mikaelkundert** [comment] 2022-04-05 14:20
I would suggest to make a performance improvement by trying to set FPS to 1 (it doesn't have to draw it faster than once a second). Or even once per minute or something. I would still like to see the progress bar :)
