### ISSUE TITLE
Task's description : Formatting Help

### ISSUE THREAD

**Issue by KiloNovemberDelta** [roldanjrCodeArts9711/productivity-timer#63] opened 2020-05-06 07:28 UTC
Hello,
Firstly, I would like to say that I love what you have developed and it is useful in my daily life. So this is why I'm taking time to perform a feedback of the v2.0.0-beta, which seems to be clearly stable in many functions. 
Using this version during a full Pomodoro time, I have seen little bug's :  
* In the description of a task, when we click to "Formatting Help", we arrive at a webpage explaining format (A really good idea btw !), but it could be nice to open it on a web browser, or have the possibility to coming back to the main application (here, I'm forced to close it to come back to it)
* This is something simple but can be annoying, when we change the title of "Task's list", and then directly create a new task, the title is not updated. 

I hope this feedback will help you, anyway great job !

**Comment by roldanjrCodeArts9711** [comment] 2020-05-06 09:55
> Hello,
> Firstly, I would like to say that I love what you have developed and it is useful in my daily life. So this is why I'm taking time to perform a feedback of the v2.0.0-beta, which seems to be clearly stable in many functions.
> Using this version during a full Pomodoro time, I have seen little bug's :
> 
> * In the description of a task, when we click to "Formatting Help", we arrive at a webpage explaining format (A really good idea btw !), but it could be nice to open it on a web browser, or have the possibility to coming back to the main application (here, I'm forced to close it to come back to it)
> * This is something simple but can be annoying, when we change the title of "Task's list", and then directly create a new task, the title is not updated.
> 
> I hope this feedback will help you, anyway great job !

Thanks for your feedback. 👍 

Regarding with "Formatting Help" I can confirm that it was a bug. And I will try to fix it ASAP.

For the "Task List Title" I'm sorry about that. That's my fault due to lack of documentation. 
The behavior expected is that you must need to enter it first to be save before you are going to create a new task but since you didn't like that I will work it out.

**Comment by KiloNovemberDelta** [comment] 2020-05-06 10:19
Great ! 
I diverge from the original issue, but it would be also awesome to have a Checkbox "Done" somewhere close to the Task's box in the Timer Window. To switch from the Task n to the next Task n+1. Mabye it is already in the road map ?

**Comment by roldanjrCodeArts9711** [comment] 2020-05-06 12:13
> have a Checkbox "Done

What do you mean? Can you produce some visualization so that it would be clear to me.

**Comment by KiloNovemberDelta** [comment] 2020-05-06 12:33
Well, I was thinking of something like this (I used paint, but it will do the job)
![Productivity_Timer_Demo](https://user-images.githubusercontent.com/41945728/81176911-279a7b00-8fa6-11ea-9e07-ba6ef8475527.png)
And then the task will be considered as done (it can be striped to be seen like done in the task's list)
By this way, we have a TODO list (list of task to be perform), a DOING task (the one you are doing during the work session) and a DONE list. 
What do you think ? Is it clear enough or do you want me to explain it more in detail ?

**Comment by roldanjrCodeArts9711** [comment] 2020-05-07 03:07
I got your point @KiloNovemberDelta but as of now I will add it on `Road Map` because I'm so very busy right now and have a lot of project deadlines to accomplish.

I hope you have `Version 2.0.3-beta` of the app now regarding with your first concern.

**Comment by KiloNovemberDelta** [comment] 2020-05-07 06:19
Yes of course I understand, I will check the 2.0.3-beta ;) 
Thanks !

**Comment by roldanjrCodeArts9711** [comment] 2020-06-01 00:35
@KiloNovemberDelta I released new version of the app with some parts of the feature you've requested. Please see [Release Notes](https://github.com/roldanjrCodeArts9711/productivity-timer/releases/tag/v2.4.0-beta) I've created for more details of changes I've made.

I hope it would help you. 

![tasks-list](https://user-images.githubusercontent.com/38913069/83366536-50b1fe00-a3e2-11ea-95d6-58182192ee07.gif)

**Comment by KiloNovemberDelta** [comment] 2020-06-02 08:01
Hi @roldanjrCodeArts9711 , that is exactly what I expected from this app, great work, thank you ! 👍  
The only thing that I don't understand is option to set a list as a "Done List". What is the functionnality behind ?

**Comment by roldanjrCodeArts9711** [comment] 2020-06-02 08:26
> Hi @roldanjrCodeArts9711 , that is exactly what I expected from this app, great work, thank you ! 👍
> The only thing that I don't understand is the option to set a list as a "Done List". What is the functionnality behind ?

The very purpose of `Done List` is when you manually drag cards to `Done List` section like Trello feature.  But I think I should remove `Done List` since marking the task `Done` is enough.

**Comment by KiloNovemberDelta** [comment] 2020-06-02 08:46
Maybe other users can find an utility for this functionnality. But as it is, for me, I don't see indeed the gain of this Done List :) 

Allow me to write another improvement's idea before I forget :
I know that Pomodoro method like to have statistic (to improve the effectiveness of the productivity). Maybe it can be added to the road map a kind of extraction of the data and let the possibility to the user to perform stats. 
I was thinking something simple, like a CSV (which can be opened by any spreadsheet, Excel or OpenOffice for example), which contains the state of each task, like : 
* Name 
* Description
* Status (TODO, ON GOING, DONE)
* Group List it belongs 
* Time dedicated (for example 3 Pomodoro time)

Of course, this implementation is not a priority, but can be a true gain for lovers of Pomodoro. 
What do you think ?
(if you want me to open another issue about this, let me know, because I'm flooding here and it is not proper)

**Comment by roldanjrCodeArts9711** [comment] 2020-06-02 09:03
Yes @KiloNovemberDelta please open another feature request and close this issue. Thank you.

**Closed** 2020-06-02 09:03 UTC
